namespace Monica.AI.Configuration.Models;

/// <summary>
/// Durable override document passed to configuration storage providers. It contains protected credentials only.
/// Do not expose this storage contract to clients; use <see cref="AIConfigurationSnapshot"/> instead.
/// </summary>
public sealed record AIConfigurationDocument
{
    /// <summary>Revision committed by the store; zero represents an absent document.</summary>
    public long Revision { get; init; }
    /// <summary>Persisted overrides, indexed by the configuration's case-insensitive provider identifier.</summary>
    public IReadOnlyList<AIPersistedProvider> Providers { get; init; } = [];
}

/// <summary>A persisted provider override with separately protected credential state.</summary>
public sealed record AIPersistedProvider
{
    /// <summary>Complete non-secret configuration that replaces the provider's code-defined baseline.</summary>
    public required AIProviderConfiguration Configuration { get; init; }
    /// <summary>Opaque, authenticated ciphertext generated by the host data-protection service, or null.</summary>
    public string? ProtectedApiKey { get; init; }
    /// <summary>Whether to use the code-defined key when no protected override is present.</summary>
    public bool UseCodeApiKey { get; init; }
}

/// <summary>Signals an optimistic concurrency conflict without silently overwriting another operator's edits.</summary>
public sealed class AIConfigurationConflictException(long expectedRevision, long actualRevision)
    : InvalidOperationException($"AI settings changed from revision {expectedRevision} to {actualRevision}. Reload settings before saving.")
{
    /// <summary>Revision supplied by the caller.</summary>
    public long ExpectedRevision { get; } = expectedRevision;
    /// <summary>Latest revision held by the store.</summary>
    public long ActualRevision { get; } = actualRevision;
}
